{% set name = "yaml-cpp" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jbeder/{{ name }}/archive/refs/tags/{{ name }}-{{ version }}.tar.gz
  sha256: 25cb043240f828a8c51beb830569634bc7ac603978e0f69d6b63558dadefd49a

build:
  number: 0

outputs:
  - name: yaml-cpp
    script: build_shared.sh  # [not win]
    script: bld_shared.bat   # [win]
    build:
      run_exports:
        - {{ pin_subpackage('yaml-cpp', max_pin='x.x') }}
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake <4
        - ninja-base
    test:
      # NOTE: Author's tests are run from the build scripts in all architectures.
      files:
        - test
      requires:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake <4
        - ninja-base
      commands:
        # These tests ensure the library is in its expected location.
        - test -f $PREFIX/lib/libyaml-cpp.so              # [linux]
        - test -f $PREFIX/lib/libyaml-cpp.dylib           # [osx]
        - if not exist %LIBRARY_BIN%\\yaml-cpp.dll exit 1 # [win]
        # These tests ensure a simple program can be built using the
        # library. They are not altogether necessary, though they are
        # nice to have.
        - test/test.sh   # [unix]
        - test/test.bat  # [win]

  - name: yaml-cpp-static
    script: build_static.sh  # [unix]
    build:
      skip: true  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake <4
        - ninja-base
      host:
        - {{ pin_subpackage('yaml-cpp', exact=True) }}
      run:
        - {{ pin_subpackage('yaml-cpp', exact=True) }}
    test:
      commands:
        - test -f $PREFIX/lib/libyaml-cpp.a  # [unix]

about:
  home: https://github.com/jbeder/yaml-cpp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
  description: yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec.
  dev_url: https://github.com/jbeder/yaml-cpp
  doc_url: https://github.com/jbeder/yaml-cpp.wiki.git

extra:
  recipe-maintainers:
    - allanleal
    - marcelotrevisani
    - tadeu
    - seanyen
    - wolfv
